#!/usr/bin/env python3
"""Regenerate test/fixtures/seed.sql from the real collection.

Run this only to refresh the fixture; the output is committed and the test
suite never touches the live shards. Real rows beat invented ones — they carry
the awkward shapes (em-dash type lines, apostrophes, DFCs, etched finishes)
that hand-written fixtures quietly omit.

    python3 scripts/make_fixture.py
"""
import re
import sqlite3
import sys
from pathlib import Path

MTG = Path.home() / ("Library/CloudStorage/GoogleDrive-mattshoe81@gmail.com/"
                     "My Drive/claude-sandbox/mtg")
OUT = Path(__file__).resolve().parent.parent / "test" / "fixtures" / "seed.sql"

# Cards chosen for shape, not for interest: a DFC, an apostrophe, a card in
# two decks, one of Kayla's, a foil and a nonfoil of the same printing.
WANTED_NAMES = [
    "sol ring", "lightning bolt", "arcane signet", "counterspell",
    "swords to plowshares", "cultivate", "rhystic study", "smothering tithe",
    "beast within", "eternal witness", "birds of paradise", "llanowar elves",
]


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    if not MTG.exists():
        sys.exit(f"collection not found at {MTG}")

    db = sqlite3.connect(":memory:")
    for shard in ("core", "text", "tags", "legal", "rulings"):
        p = MTG / f"collection-{shard}.db"
        db.execute("ATTACH DATABASE ? AS " + shard, (f"file:{p}?mode=ro&immutable=1",))
    db.row_factory = sqlite3.Row

    names = ",".join("?" * len(WANTED_NAMES))
    picked = db.execute(f"""
        SELECT * FROM core.cards
         WHERE name_norm IN ({names})
            OR name_norm LIKE '%//%'
            OR finish != 'nonfoil'
            OR name LIKE '%''%'
         ORDER BY owner, name_norm, finish
         LIMIT 60
    """, WANTED_NAMES).fetchall()

    # A handful of basics, so land counts and the BASICS carve-out are covered.
    picked += db.execute("""
        SELECT * FROM core.cards
         WHERE name_norm IN ('forest','island','plains') LIMIT 6
    """).fetchall()

    ids = [r["id"] for r in picked]
    idlist = ",".join(str(i) for i in ids)
    cols = [d[0] for d in db.execute("SELECT * FROM core.cards LIMIT 1").description]

    lines = [
        "-- Generated by scripts/make_fixture.py. Real rows from the collection,",
        "-- narrowed to the shapes the tests care about. Do not hand-edit.",
        "",
    ]

    def dump(table, rows, columns):
        if not rows:
            return
        lines.append(f"-- {table} ({len(rows)})")
        for r in rows:
            vals = ",".join(q(r[c]) for c in columns)
            lines.append(f"INSERT INTO {table} ({','.join(columns)}) VALUES ({vals});")
        lines.append("")

    dump("cards", picked, cols)

    for table, key in [("card_faces", "card_id"), ("card_colors", "card_id"),
                       ("card_types", "card_id"), ("card_keywords", "card_id"),
                       ("card_finishes", "card_id"), ("card_games", "card_id"),
                       ("card_promo_types", "card_id"),
                       ("card_frame_effects", "card_id")]:
        rows = db.execute(f"SELECT * FROM core.{table} WHERE {key} IN ({idlist})").fetchall()
        dump(table, rows, [d[0] for d in db.execute(f"SELECT * FROM core.{table} LIMIT 1").description])

    rows = db.execute(f"SELECT * FROM tags.card_tags WHERE card_id IN ({idlist})").fetchall()
    dump("card_tags", rows, ["card_id", "tag_slug", "kind"])

    slugs = sorted({r["tag_slug"] for r in rows})
    if slugs:
        tagrows = db.execute(
            "SELECT * FROM tags.tags WHERE slug IN (%s)" % ",".join("?" * len(slugs)), slugs
        ).fetchall()
        dump("tags", tagrows, ["slug", "kind", "label", "description"])

    oids = sorted({r["oracle_id"] for r in picked if r["oracle_id"]})
    if oids:
        ph = ",".join("?" * len(oids))
        dump("legalities",
             db.execute(f"SELECT * FROM legal.legalities WHERE oracle_id IN ({ph})", oids).fetchall(),
             ["oracle_id", "format", "status"])
        dump("rulings",
             db.execute(f"SELECT * FROM rulings.rulings WHERE oracle_id IN ({ph}) LIMIT 40", oids).fetchall(),
             ["oracle_id", "published_at", "source", "comment"])

    # Three decks: a real one, a proxy, and a PROPOSED one, so the view
    # predicates have something to discriminate between.
    decks = db.execute("""
        SELECT * FROM core.decks
         WHERE is_proxy = 1
            OR status LIKE 'PROPOSED%'
            OR (is_proxy = 0 AND (status IS NULL OR status NOT LIKE 'PROPOSED%'))
         ORDER BY is_proxy DESC, id LIMIT 4
    """).fetchall()
    dcols = [d[0] for d in db.execute("SELECT * FROM core.decks LIMIT 1").description]
    # source_md is a whole markdown file; the tests never read it.
    decks = [{**dict(r), "source_md": None} for r in decks]
    dump("decks", decks, dcols)

    if decks:
        dids = ",".join(str(d["id"]) for d in decks)
        dc = db.execute(f"""
            SELECT * FROM core.deck_cards WHERE deck_id IN ({dids})
              AND (name_norm IN (SELECT name_norm FROM core.cards WHERE id IN ({idlist}))
                   OR in_collection = 0)
             LIMIT 60
        """).fetchall()
        dump("deck_cards", dc, [d[0] for d in db.execute("SELECT * FROM core.deck_cards LIMIT 1").description])
        dump("deck_notes",
             db.execute(f"SELECT * FROM core.deck_notes WHERE deck_id IN ({dids}) LIMIT 5").fetchall(),
             ["id", "deck_id", "section", "body"])

    dump("aliases",
         db.execute(f"""SELECT DISTINCT lower(face1) AS alias_norm, name AS canonical_name
                          FROM core.cards WHERE id IN ({idlist})""").fetchall(),
         ["alias_norm", "canonical_name"])

    lines += [
        "-- Full-text rows, rebuilt from what was inserted above.",
        "INSERT INTO card_search (rowid, name, type_line, oracle_text, flavor_text, keywords, tags)",
        "SELECT c.id, c.name, c.type_line, c.oracle_text, c.flavor_text,",
        "       (SELECT GROUP_CONCAT(keyword,' ') FROM card_keywords k WHERE k.card_id = c.id),",
        "       (SELECT GROUP_CONCAT(tag_slug,' ') FROM card_tags t WHERE t.card_id = c.id)",
        "FROM cards c;",
        "",
    ]

    OUT.write_text("\n".join(lines))
    print(f"{OUT}: {len(picked)} cards, {sum(1 for l in lines if l.startswith('INSERT'))} inserts")


if __name__ == "__main__":
    main()
