#!/usr/bin/env python3
"""Regenerate test/fixtures/seed.sql from the real collection.

Run this only to refresh the fixture; the output is committed and the test
suite never touches the live shards. Real rows beat invented ones — they carry
the awkward shapes (em-dash type lines, apostrophes, DFCs, etched finishes)
that hand-written fixtures quietly omit.

    python3 scripts/make_fixture.py

Reads the live API, not the retired Drive shards: those are frozen at the
migration, so a fixture built from them would drift further from the real
data every week while looking freshly generated.

Note that basic lands and tokens are no longer in the collection, so a
regenerated fixture will not contain any. Tests that need one must make it
up rather than expect it here.
"""
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

API = "https://mtg-api.mattshoe81.workers.dev"
OUT = Path(__file__).resolve().parent.parent / "test" / "fixtures" / "seed.sql"


def api(sql, params=()):
    """Rows as dicts, plus the column order the API reported."""
    body = json.dumps({"sql": sql, "params": list(params), "fmt": "rows"}).encode()
    req = urllib.request.Request(
        API + "/query", data=body,
        headers={"Content-Type": "application/json", "User-Agent": "mtg-fixture/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            payload = json.load(r)
    except urllib.error.HTTPError as e:
        sys.exit(f"API {e.code}: {e.read().decode()[:300]}")
    if payload.get("error"):
        sys.exit(f"API rejected: {payload['error']}\n  {sql}")
    cols = payload.get("cols", [])
    return [dict(zip(cols, row)) for row in payload.get("rows", [])], cols


def rows(sql, params=()):
    return api(sql, params)[0]


def columns(table):
    return api(f"SELECT * FROM {table} LIMIT 1")[1]


# D1 refuses more than 100 bound parameters in one statement, and the tag
# slugs alone run well past that.
CHUNK = 90


def rows_in(sql_template, values, extra=()):
    """Run `sql_template` once per chunk of `values`, concatenating the rows.

    The template takes a single `{ph}` where the placeholder list goes.
    """
    out = []
    for i in range(0, len(values), CHUNK):
        slice_ = values[i:i + CHUNK]
        ph = ",".join("?" * len(slice_))
        out += rows(sql_template.format(ph=ph), [*slice_, *extra])
    return out

# Cards chosen for shape, not for interest: a DFC, an apostrophe, a card in
# two decks, one of Kayla's, a foil and a nonfoil of the same printing.
WANTED_NAMES = [
    "sol ring", "lightning bolt", "arcane signet", "counterspell",
    "swords to plowshares", "cultivate", "rhystic study", "smothering tithe",
    "beast within", "eternal witness", "birds of paradise", "llanowar elves",
]


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    names = ",".join("?" * len(WANTED_NAMES))
    picked = rows(f"""
        SELECT * FROM cards
         WHERE name_norm IN ({names})
            OR name_norm LIKE '%//%'
            OR finish != 'nonfoil'
            OR name LIKE '%''%'
         ORDER BY owner, name_norm, finish
         LIMIT 60
    """, WANTED_NAMES)

    # Basics used to be seeded here. They were removed from the collection on
    # purpose, so there are none to take.

    ids = [r["id"] for r in picked]
    idlist = ",".join(str(i) for i in ids)
    cols = columns("cards")

    lines = [
        "-- Generated by scripts/make_fixture.py. Real rows from the collection,",
        "-- narrowed to the shapes the tests care about. Do not hand-edit.",
        "",
    ]

    def dump(table, rows, columns):
        if not rows:
            return
        lines.append(f"-- {table} ({len(rows)})")
        for r in rows:
            vals = ",".join(q(r[c]) for c in columns)
            lines.append(f"INSERT INTO {table} ({','.join(columns)}) VALUES ({vals});")
        lines.append("")

    dump("cards", picked, cols)

    for table, key in [("card_faces", "card_id"), ("card_colors", "card_id"),
                       ("card_types", "card_id"), ("card_keywords", "card_id"),
                       ("card_finishes", "card_id"), ("card_games", "card_id"),
                       ("card_promo_types", "card_id"),
                       ("card_frame_effects", "card_id")]:
        child = rows(f"SELECT * FROM {table} WHERE {key} IN ({idlist})")
        dump(table, child, columns(table))

    tagged = rows(f"SELECT * FROM card_tags WHERE card_id IN ({idlist})")
    dump("card_tags", tagged, ["card_id", "tag_slug", "kind"])

    slugs = sorted({r["tag_slug"] for r in tagged})
    if slugs:
        tagrows = rows_in("SELECT * FROM tags WHERE slug IN ({ph})", slugs)
        dump("tags", tagrows, ["slug", "kind", "label", "description"])

    oids = sorted({r["oracle_id"] for r in picked if r["oracle_id"]})
    if oids:
        dump("legalities",
             rows_in("SELECT * FROM legalities WHERE oracle_id IN ({ph})", oids),
             ["oracle_id", "format", "status"])
        dump("rulings",
             rows_in("SELECT * FROM rulings WHERE oracle_id IN ({ph})", oids)[:40],
             ["oracle_id", "published_at", "source", "comment"])

    # Three decks: a real one, a proxy, and a PROPOSED one, so the view
    # predicates have something to discriminate between.
    decks = rows("""
        SELECT * FROM decks
         WHERE is_proxy = 1
            OR status LIKE 'PROPOSED%'
            OR (is_proxy = 0 AND (status IS NULL OR status NOT LIKE 'PROPOSED%'))
         ORDER BY is_proxy DESC, id LIMIT 4
    """)
    dcols = columns("decks")
    # source_md is a whole markdown file; the tests never read it.
    decks = [{**dict(r), "source_md": None} for r in decks]
    dump("decks", decks, dcols)

    if decks:
        dids = ",".join(str(d["id"]) for d in decks)
        dc = rows(f"""
            SELECT * FROM deck_cards WHERE deck_id IN ({dids})
              AND (name_norm IN (SELECT name_norm FROM cards WHERE id IN ({idlist}))
                   OR in_collection = 0)
             LIMIT 60
        """)
        dump("deck_cards", dc, columns("deck_cards"))
        dump("deck_notes",
             rows(f"SELECT * FROM deck_notes WHERE deck_id IN ({dids}) LIMIT 5"),
             ["id", "deck_id", "section", "body"])

    dump("aliases",
         rows(f"""SELECT DISTINCT lower(face1) AS alias_norm, name AS canonical_name
                    FROM cards WHERE id IN ({idlist}) AND face1 IS NOT NULL"""),
         ["alias_norm", "canonical_name"])

    lines += [
        "-- Full-text rows, rebuilt from what was inserted above.",
        "INSERT INTO card_search (rowid, name, type_line, oracle_text, flavor_text, keywords, tags)",
        "SELECT c.id, c.name, c.type_line, c.oracle_text, c.flavor_text,",
        "       (SELECT GROUP_CONCAT(keyword,' ') FROM card_keywords k WHERE k.card_id = c.id),",
        "       (SELECT GROUP_CONCAT(tag_slug,' ') FROM card_tags t WHERE t.card_id = c.id)",
        "FROM cards c;",
        "",
    ]

    OUT.write_text("\n".join(lines))
    print(f"{OUT}: {len(picked)} cards, {sum(1 for l in lines if l.startswith('INSERT'))} inserts")


if __name__ == "__main__":
    main()
