#!/usr/bin/env python3
"""SPENT — the one-time migration, kept for the record. Do not run it.

Export the five collection shards as one data.sql for `wrangler d1 import`.

This ran once, on 2026-09-26. The shards it reads have been frozen ever
since and D1 has moved on, so running it again would overwrite the live
collection with a pre-migration snapshot.

The shards are opened read-only and immutable. This script never writes to
them, and the old pipeline keeps running while it reads.

What is deliberately left out:
  totals      - now a view over cards
  db_meta     - the staleness protocol the sharding needed, gone with it
  card_search - FTS5 shadow tables cannot be dumped as INSERTs; the rows are
                rebuilt from cards after the import, which is what the old
                builder did too
  sqlite_sequence - SQLite maintains it

    python3 scripts/seed.py [--out data.sql]
"""
import argparse
import sqlite3
import sys
from pathlib import Path

MTG = Path.home() / ("Library/CloudStorage/GoogleDrive-mattshoe81@gmail.com/"
                     "My Drive/claude-sandbox/mtg")
SHARDS = ["core", "text", "tags", "legal", "rulings"]

# Every table that carries data, in an order that respects the one foreign
# key that exists (deck_cards and deck_notes point at decks).
TABLES = [
    "cards", "card_faces", "card_colors", "card_types", "card_keywords",
    "card_finishes", "card_games", "card_promo_types", "card_frame_effects",
    "aliases", "decks", "deck_cards", "deck_notes",
    "card_tags", "tags", "legalities", "rulings",
]

# D1 rejects an oversized statement (SQLITE_TOOBIG), and a `cards` row with
# full oracle and flavor text is not small. Batch by bytes, not by row count.
MAX_STATEMENT_BYTES = 80_000
MAX_ROWS_PER_INSERT = 500


def quote(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, bytes):
        return "X'" + v.hex() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def connect():
    if not MTG.exists():
        sys.exit(f"collection not found at {MTG}")
    db = sqlite3.connect(":memory:")
    for shard in SHARDS:
        p = MTG / f"collection-{shard}.db"
        if not p.exists():
            sys.exit(f"missing shard {p}")
        db.execute(f"ATTACH DATABASE ? AS {shard}", (f"file:{p}?mode=ro&immutable=1",))
    return db


def locate(db, table):
    """Which shard holds this table? The split is an implementation detail."""
    for shard in SHARDS:
        row = db.execute(
            f"SELECT 1 FROM {shard}.sqlite_master WHERE type='table' AND name=?", (table,)
        ).fetchone()
        if row:
            return shard
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data.sql")
    args = ap.parse_args()

    db = connect()
    out = Path(args.out)
    total = 0

    with out.open("w") as f:
        f.write("-- Generated by scripts/seed.py from the five collection shards.\n")
        f.write("-- One-time migration payload for `wrangler d1 import`.\n\n")

        for table in TABLES:
            shard = locate(db, table)
            if shard is None:
                print(f"  skip {table}: not in any shard", file=sys.stderr)
                continue

            cur = db.execute(f"SELECT * FROM {shard}.{table}")
            cols = [d[0] for d in cur.description]
            collist = ",".join(cols)

            n = 0
            batch = []
            size = 0

            def flush():
                nonlocal batch, size, n
                if not batch:
                    return
                f.write(f"INSERT INTO {table} ({collist}) VALUES\n"
                        + ",\n".join(batch) + ";\n")
                n += len(batch)
                batch = []
                size = 0

            for row in cur:
                tup = "(" + ",".join(quote(v) for v in row) + ")"
                if batch and (size + len(tup) > MAX_STATEMENT_BYTES
                              or len(batch) >= MAX_ROWS_PER_INSERT):
                    flush()
                batch.append(tup)
                size += len(tup) + 2
            flush()

            f.write("\n")
            total += n
            print(f"  {table}: {n}")

        # The FTS index is rebuilt rather than copied. Identical to what
        # build_collection_db.py does at the end of every build.
        f.write("-- Full-text index, rebuilt from the rows above.\n")
        f.write(
            "INSERT INTO card_search (rowid, name, type_line, oracle_text,"
            " flavor_text, keywords, tags)\n"
            "SELECT c.id, c.name, c.type_line, c.oracle_text, c.flavor_text,\n"
            "       (SELECT GROUP_CONCAT(keyword,' ') FROM card_keywords k"
            " WHERE k.card_id = c.id),\n"
            "       (SELECT GROUP_CONCAT(tag_slug,' ') FROM card_tags t"
            " WHERE t.card_id = c.id)\n"
            "FROM cards c;\n"
        )

    size = out.stat().st_size
    print(f"\n{out}: {total} rows, {size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
